name: My first action

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
